spring.application.name=FileService
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/file_service}
server.port=${PORT:5003}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
